[build]
  # Directory with the deployable files
  publish = "public"
  
  # No build command needed for static site
  command = "echo 'Static site - no build needed'"

[build.environment]
  # Node version for any server functions
  NODE_VERSION = "18"

# Redirect all routes to index.html for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"